name: Function App Deployment

on:
    workflow_dispatch:
        inputs:
            customer:
                description: "Customer name"
                required: true
                default: 'xoc'
                options:
                    - xoc
                    - llm
                    - fbi
                    - nasa
                type: choice
            rgname:
                description: "Resource group name"
                required: true
                default: ''
                type: string
            faname:
                description: "Function app name"
                required: true
                default: ''
                type: string
            acname:
                description: "App Configuration name"
                required: true
                default: ''
                type: string
            dsname:
                description: "Name of deployment stack"
                required: true
                default: ''
                type: string
            aaname:
                description: "Automation Account name"
                required: true
                default: ''
                type: string

permissions:
    id-token: write
    contents: read

env:
    Customer: ${{github.event.inputs.customer}}
    TenantId: ${{secrets.AZURE_TENANT_ID}}
    DeploymentStackName: ${{github.event.inputs.dsname}}
    functionAppName: ${{github.event.inputs.faname}}
    AzFaAppRegClient: ${{secrets.AZURE_FUNCTION_APP_CLIENT}}
    ResourceGroupName: ${{github.event.inputs.rgname}}
    AppConfigName: ${{github.event.inputs.acname}}
    AutomationAccountname: ${{github.event.inputs.aaname}}

jobs:
    FunctionAppDeployment:
        name: Function App Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
                
            - name: Function App Deployment
              uses: azure/cli@v2
              with:
                azcliversion: 'latest'
                inlineScript: |
                    az stack group create --name $DeploymentStackName --resource-group $ResourceGroupName --parameters ./IaC/main.bicepparam --action-on-unmanage deleteResources --deny-settings-mode none

            - name: Create App configuration file
              run: |
                input_file="./IaC/Templates/AppConfiguration/keys.json"
                jq --arg funcAppNameVal "$functionAppName" \
                   --arg resGroupNameVal "$ResourceGroupName" \
                   'if .FunctionAppName == "" then .FunctionAppName = $funcAppNameVal else . end |
                    if .ResourceGroupName == "" then .ResourceGroupName = $resGroupNameVal else . end' \
                   $input_file > appsettings.json
            
            - name: Import configuration file to App Configuration
              uses: azure/cli@v2
              with:
                azcliversion: 'latest'
                inlineScript: |
                    az appconfig kv import --name $AppConfigName --auth-mode login --source file --path appsettings.json --format json --separator : --yes # User assigned managed identity should be assigned the role of App config data owner


        