name: Test workflow

on:
  workflow_dispatch:
    inputs:
      customer:
        description: "Customer name"
        required: true
        default: "XOC"
        options:
          - XOC
          - BBX
          - AVA
          - DSS
        type: choice

env:
  Customer: ${{github.event.inputs.customer}}

jobs:
  FunctionApp:
    if: github.ref_head == 'cat' || github.ref_head == 'main'
    name: Function App Name
    runs-on: ubuntu-latest
    environment: ${{github.ref_head=='cat' && 'cat' || github.ref_head=='main' && 'prod'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Function App name
        env:
          FunctionAppName:${{vars.AZ_FUNCTIONAPPNAME}}
          ResourceGroupName:${{vars.AZ_RESOURCEGROUPNAME}}
          Environment:${{github.ref_head == 'cat' && 'CAT' || github.ref_head == 'main' && 'PROD'}}
        run: |
          echo "Function App Name: $FunctionAppName"
          echo "Resource Group Name: $ResourceGroupName"
          echo "Key Vault Name: kv-BoC-${Customer}${Environment}"
