name: Test workflow

on:
  workflow_dispatch:
    inputs:
      customer:
        description: "Customer name"
        required: true
        default: "XOC"
        options:
          - XOC
          - BBX
          - AVA
          - DSS
        type: choice

env:
  Customer: ${{github.event.inputs.customer}}
  Environment: ${{github.ref_name == 'cat' && 'CAT' || github.ref_name == 'main' && 'PROD'}}
  KeyVaultName: "kv-BoC-${Customer}${Environment}"

jobs:
  FunctionApp:
    if: github.ref_name == 'cat' || github.ref_name == 'main'
    name: Function App Name
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'cat' && 'cat' || github.ref_name == 'main' && 'prod'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Function App name
        env:
          FunctionAppName: ${{vars.AZ_FUNCTIONAPPNAME}}
          ResourceGroupName: ${{vars.AZ_RESOURCEGROUPNAME}}
        run: |
          echo "Function App Name: ${FunctionAppName}"
          echo "Resource Group Name: ${ResourceGroupName}"
          echo "Key Vault Name: ${KeyVaultName}"
