name: Test workflow

on:
  workflow_dispatch:
    inputs:
      customer:
        description: "Customer name"
        required: true
        default: "XOC"
        options:
          - XOC
          - BBX
          - AVA
          - DSS
        type: choice
      environment:
        description: "Deployment environment"
        required: true
        default: "CAT"
        options:
          - CAT
          - PROD
        type: choice

env:
  Customer: ${{github.event.inputs.customer}}
  Environment: ${{github.event.inputs.environment}}
  CustomerLower: $(echo ${{github.event.inputs.customer}} | tr '[:upper:]' '[:lower:]')
  EnvironmentLower: $(echo ${{github.event.inputs.environment}} | tr '[:upper:]' '[:lower:]')
  FunctionAppName: "fa-boc-${CustomerLower}${EnvironmentLower}"
  AppConfigurationName: "ac-boc-${CustomerLower}${EnvironmentLower}"

jobs:
  FunctionApp:
    name: Function App Name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Function App name
        run: |
          echo ${FunctionAppName}
    
  AppConfiguration:
    name: App Configuration Name
    needs: FunctionApp
    runs-on: ubutnu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print App configuration name
        run: |
          echo ${AppConfigurationName}
